/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Grouped.java
 *
 * Created on Feb 24, 2019, 2:13:40 AM
 */

package traffic_mgmt;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Grouped extends javax.swing.JFrame {

    /** Creates new form Grouped */
    public Grouped() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        l2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setText("Enter First Member Unique ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 120, 178, 16);

        jLabel6.setText("Enter Company Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 430, 124, 16);

        jLabel4.setText("Enter Second Member Unique ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 190, 195, 16);

        jLabel5.setText("Enter Vehicle No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 350, 98, 16);

        jLabel1.setText("UNIQUE ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 50, 65, 16);

        l1.setText("jLabel2");
        jPanel1.add(l1);
        l1.setBounds(130, 50, 41, 16);

        jLabel2.setText("Enter First Member Unique ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 270, 178, 16);
        jPanel1.add(t1);
        t1.setBounds(490, 120, 260, 22);
        jPanel1.add(t2);
        t2.setBounds(490, 190, 260, 22);
        jPanel1.add(t3);
        t3.setBounds(490, 270, 260, 22);
        jPanel1.add(t4);
        t4.setBounds(490, 350, 260, 22);

        jLabel7.setText("Create a Group");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 60, 130, 16);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 550, 130, 60);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A 10 Amazon", "A 12 Microsoft" }));
        jPanel1.add(c1);
        c1.setBounds(490, 430, 260, 22);

        l2.setVisible(false);
        l2.setText("jLabel2");
        jPanel1.add(l2);
        l2.setBounds(620, 20, 90, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String m1 = t1.getText();
String m2 = t2.getText();
String m3 = t3.getText();
String v = t4.getText();
String comp = c1.getSelectedItem().toString();

try{

        Class.forName("java.sql.Driver");
        Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/traffic","root","help");
        Statement stmt = con.createStatement();
String c = "SELECT COUNT(grp_no) FROM grp;";
ResultSet rs = stmt.executeQuery(c);
if(rs.next())
{int dno = rs.getInt("COUNT(grp_no)");
l2.setText(""+dno);}
       int dn = Integer.parseInt(l2.getText());
       String q = "INSERT INTO grp VALUES ('"+dn+"','"+m1+"','"+m2+"','"+m3+"','"+v+"','"+comp+"'); ";
       stmt.executeUpdate(q);

}
catch(Exception e )
{JOptionPane.showMessageDialog(null,e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grouped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables

}
