/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Grouped.java
 *
 * Created on Feb 24, 2019, 2:13:40 AM
 */

package traffic_mgmt;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Grouped extends javax.swing.JFrame {

    /** Creates new form Grouped */
    public Grouped() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
  public Grouped(String parad) {
        initComponents();
        l1.setText(parad);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        l2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Enter First Member Unique ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 150, 353, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Enter Company Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 460, 248, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Enter Second Member Unique ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 220, 400, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Enter Vehicle No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 380, 198, 29);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText("UNIQUE ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 110, 22);

        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/Mini.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(870, 10, 50, 40);

        l1.setFont(new java.awt.Font("Arial", 1, 18));
        l1.setText("jLabel2");
        jPanel1.add(l1);
        l1.setBounds(130, 80, 90, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Enter First Member Unique ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 300, 353, 29);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Create a Group");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 17, 180, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/crs.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(940, 10, 50, 40);

        t1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(560, 150, 260, 35);

        t2.setFont(new java.awt.Font("Arial", 1, 24));
        jPanel1.add(t2);
        t2.setBounds(560, 220, 260, 35);

        t3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel1.add(t3);
        t3.setBounds(560, 300, 260, 35);

        t4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(560, 380, 260, 35);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Create a Group");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 90, 190, 30);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 630, 120, 50);

        c1.setFont(new java.awt.Font("Arial", 1, 24));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A 10 Amazon", "A 12 Microsoft" }));
        jPanel1.add(c1);
        c1.setBounds(560, 460, 260, 30);

        l2.setVisible(false);
        l2.setText("jLabel2");
        jPanel1.add(l2);
        l2.setBounds(620, 20, 90, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/tool.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -4, 1010, 70);

        jButton2.setText("Go to Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(780, 630, 110, 50);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(110, 630, 110, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/WhatsApp Image 2019-02-23 at 3.45.38 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 60, 1010, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String m1 = t1.getText();
String m2 = t2.getText();
String m3 = t3.getText();
String v = t4.getText();
String comp = c1.getSelectedItem().toString();
if(m1.equalsIgnoreCase("")||m2.equalsIgnoreCase("")||m3.equalsIgnoreCase("")||v.equalsIgnoreCase("")||comp.equalsIgnoreCase(""))
{JOptionPane.showMessageDialog(null,"Enter Proper details");}
else {
try{

        Class.forName("java.sql.Driver");
        Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/traffic","root","help");
        Statement stmt = con.createStatement();
String c = "SELECT COUNT(grp_no) FROM grp;";
ResultSet rs = stmt.executeQuery(c);
if(rs.next())
{int dno = rs.getInt("COUNT(grp_no)");
l2.setText(""+dno);}
       int dn = Integer.parseInt(l2.getText());
       String q = "INSERT INTO grp VALUES ('"+dn+"','"+m1+"','"+m2+"','"+m3+"','"+v+"','"+comp+"'); ";
       stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Group Created Successfully");

}
catch(Exception e )
{JOptionPane.showMessageDialog(null,e.getMessage());}
} // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(ICONIFIED);        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String uni = l1.getText();
        Profile nw = new Profile(uni);
        nw.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String uni = l1.getText();
members ne = new members(uni);
ne.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grouped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables

}
