/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lead.java
 *
 * Created on Feb 24, 2019, 10:13:38 AM
 */

package traffic_mgmt;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author HP
 */
public class lead extends javax.swing.JFrame {
 private Timer t;
    /** Creates new form lead */
    public lead() {
        initComponents();
  this.setLocationRelativeTo(null);  }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        p1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        l1.setVisible(false);
        jPanel1.add(l1);
        l1.setBounds(0, 0, 0, 0);

        jButton2.setVisible(false);
        jButton2.setText("Go!!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 490, 70, 30);

        l2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        l2.setForeground(new java.awt.Color(51, 0, 255));
        l2.setText("Loading....");
        jPanel1.add(l2);
        l2.setBounds(430, 500, 70, 17);

        t1.setVisible(false);
        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(0, 0, 6, 22);

        jLabel3.setFont(new java.awt.Font("Blackadder ITC", 0, 100));
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Hassle Free Ghaziabad");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 190, 870, 123);

        int v =p1.getValue();;
        if(v<100)
        {
            t = new Timer(400, new ActionListener()

                {
                    @Override
                    public void actionPerformed(ActionEvent e ){
                        int v =p1.getValue();;

                        v=v+10;
                        l1.setText(""+v);
                        p1.setValue(v);
                        t1.setText(""+v);

                    }

                }

            );
        }t.start();
        p1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        p1.setForeground(new java.awt.Color(102, 102, 255));
        p1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1StateChanged(evt);
            }
        });
        p1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                p1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.add(p1);
        p1.setBounds(320, 420, 290, 30);

        jLabel4.setFont(new java.awt.Font("Blackadder ITC", 0, 100));
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("We Will definitely achieve");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 940, 123);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/3204246053_11cb644f15_b.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login frame2 = new Login();
        frame2.setVisible(true);

        this.setVisible(false);



        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
        p1.setStringPainted(true);

        if(t1.getText().equals("110")) {
            p1.setString("Done !!");
        } else {
            p1.setString(t1.getText()+"%");
        }



        if(t1.getText().equals("110")) {
            l2.setVisible(false);
            jButton2.setVisible(true);

        }

        // TODO add your handling code here:
}//GEN-LAST:event_t1CaretUpdate

    private void p1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1StateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_p1StateChanged

    private void p1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_p1CaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_p1CaretPositionChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JProgressBar p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
