/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update_bio.java
 *
 * Created on Feb 24, 2019, 7:00:04 AM
 */

package traffic_mgmt;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Update_bio extends javax.swing.JFrame {

    /** Creates new form Update_bio */
    public Update_bio() {
        initComponents();this.setLocationRelativeTo(null); 
    }
    public Update_bio(String para )
    {
    initComponents();
    l1.setText(para);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Update Your Profile");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 20, 180, 30);

        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/Mini.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(870, 10, 50, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/crs.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(940, 10, 50, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/tool.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -4, 1010, 70);

        l2.setFont(new java.awt.Font("Arial", 0, 24));
        l2.setVisible(false);
        l2.setText("What To Change ?");
        jPanel1.add(l2);
        l2.setBounds(190, 280, 330, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mobile No.", "Residence Mobile No.", "Vehicle No.", "Vehicle Name", "Email Id" }));
        c1.setToolTipText("");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(630, 180, 250, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel2.setText("What To Change ?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 180, 210, 30);

        t1.setVisible(false);
        jPanel1.add(t1);
        t1.setBounds(630, 290, 250, 22);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 390, 130, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel3.setText("UNIQUE ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 130, 30);

        l1.setFont(new java.awt.Font("Arial", 1, 18));
        l1.setText("T322138979");
        jPanel1.add(l1);
        l1.setBounds(160, 100, 160, 30);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 390, 90, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traffic_mgmt/WhatsApp Image 2019-02-23 at 3.45.38 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 60, 1010, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(ICONIFIED);        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
int i = c1.getSelectedIndex();
String na;
switch(i)
{case 0 : JOptionPane.showMessageDialog(null,"Please Select an option");
break;
    case 1:na = "mob";
    t1.setVisible(true);
    l2.setVisible(true);
    l2.setText("Enter New Mobile Number");
    break ;
    case 2 : na = "res_mob";t1.setVisible(true);
   l2.setVisible(true);
    l2.setText("Enter New Residence Mobile Number");
     break;
    case 3: na ="veh_no";t1.setVisible(true);
    l2.setVisible(true);
    l2.setText("Enter Vehicle Number");
    break ;
    case 4 : na ="veh_name";t1.setVisible(true);
        l2.setVisible(true);
    l2.setText("Enter New Vehicle Name");
    break;
    case 5:na ="gmai";t1.setVisible(true);
        l2.setVisible(true);
    l2.setText("Enter New Emmail ID");


}

        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


try {
    String nw = t1.getText();
    int i = c1.getSelectedIndex();
String na="";
switch(i)
{case 0 : JOptionPane.showMessageDialog(null,"Please Select an option");
break;
    case 1:na = "mob";
    t1.setVisible(true);
    l2.setVisible(true);
    l2.setText("Enter New Mobile Number");
    break ;
    case 2 : na = "res_mob";t1.setVisible(true);
   l2.setVisible(true);
    l2.setText("Enter New Residence Mobile Number");
     break;
    case 3: na ="veh_no";t1.setVisible(true);
    l2.setVisible(true);
    l2.setText("Enter Vehicle Number");
    break ;
    case 4 : na ="veh_name";t1.setVisible(true);
        l2.setVisible(true);
    l2.setText("Enter New Vehicle Name");
    break;
    case 5:na ="gmai";t1.setVisible(true);
        l2.setVisible(true);
    l2.setText("Enter New Emmail ID");


}
String uni = l1.getText();
    Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/traffic", "root", "help");
            Statement stmt = conn.createStatement();
String query = "UPDATE register SET "+na+" = '"+nw+"' WHERE uni_id = '"+uni+"'; ";
stmt.executeUpdate(query);
JOptionPane.showMessageDialog(null,"Data Updated Successfully");
l2.setVisible(false);
t1.setVisible(false);
c1.setSelectedIndex(0);
t1.setText("");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String uni = l1.getText();
        Profile nw = new Profile(uni);
        nw.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_bio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
